# Generated by Django 5.0.4 on 2024-05-08 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0004_remove_travelbook_user_customuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbook',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
