# Generated by Django 5.0.4 on 2024-05-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourapp', '0007_profile_delete_userregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelbook',
            name='user',
        ),
    ]
